language: python

cache: pip

python:
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - libdb-dev

env:
  - TARGET=lint
  - TARGET=typecheck
  - TARGET=unit-tests

script: BERKELEYDB_DIR=/usr make $TARGET -e py_env=~/virtualenv/python$TRAVIS_PYTHON_VERSION
